### ISSUE TITLE
Merge new code

### ISSUE THREAD

**Issue by hargup** [AGV-IIT-KGP/freezing-batman#143]
The code for Eklavay 4.0 is in @abinashmeher999 's personal repo https://github.com/abinashmeher999/eklavya-2015, we should maintain only one codebase and the code in the eklavya-2015 repo should be merged in this one.

**Comment by abinashmeher999** [comment]
How about I transfer the ownership?

**Comment by hargup** [comment]
Sure I'll you to the owners list.

**Comment by hargup** [comment]
Oh sorry, misread you. Transferring the ownership of the repo won't help, because even them there will be two code bases.

**Comment by abinashmeher999** [comment]
I will delete mine then, and have others update their upstream

_Regards,_

_Abinash Meher_

**Comment by abinashmeher999** [comment]
I transferred it, and I don't see the repo eklavya-2015 listed in my list of repos

**Comment by abinashmeher999** [comment]
@hargup I guess this can be closed now
