### ISSUE TITLE
Write code for JAUS challenge.

### ISSUE THREAD

**Issue by hargup** [AGV-IIT-KGP/freezing-batman#32]
Read the IGVC doc, read the specifications and write the code for JAUS challenge.

**Comment by hargup** [comment]
@abinashmeher999, @krishna95  Did we participate in the JAUS challenge this year?

**Comment by abinashmeher999** [comment]
No, we didn't. This is the same as the IOP challenge, right?

**Comment by ayush9pandey** [comment]
Yeah, with some changes I guess. Maybe that's why they renamed it.

On Sun, Jun 14, 2015 at 10:54 PM, Abinash Meher notifications@github.com
wrote:

> No, we didn't. This is the same as the IOP challenge, right?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AGV-IIT-KGP/freezing-batman/issues/32#issuecomment-111934505
> .

## 

Regards,

Ayush Pandey
Department of Electrical Engineering
IIT Kharagpur
Personal Webpage: ayush9pandey.wix.com/ayushpandey

**Comment by hargup** [comment]
Okay, so we participated in the IOP challenge. I don't see the code in the repo, please add it.

**Comment by ayush9pandey** [comment]
No we didn't. Hence, no code.
We are not in a position I guess. The auto-nav challenge code itself is not
in a good shape and maybe we should focus more and more on that then only
think about IOP challenge. But, obviously added to this goes that if
somebody finds the challenge interesting then he/she is most welcome to do
something.

On Sun, Jun 14, 2015 at 11:10 PM, Harsh Gupta notifications@github.com
wrote:

> Closed #32 https://github.com/AGV-IIT-KGP/freezing-batman/issues/32.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AGV-IIT-KGP/freezing-batman/issues/32#event-330693258
> .

## 

Regards,

Ayush Pandey
Department of Electrical Engineering
IIT Kharagpur
Personal Webpage: ayush9pandey.wix.com/ayushpandey

**Comment by hargup** [comment]
Got it.  I also see the Abinash other people worked on a seperate repo https://github.com/abinashmeher999/eklavya-2015 for this year's work.

**Comment by ayush9pandey** [comment]
Yeah, I guess controls and some other people did create repos without
considering the fact that all should be united. There are some others as
well. It would be great if you or somebody could look into this and merge
it all together or do whatever as you see fit.

On Sun, Jun 14, 2015 at 11:28 PM, Harsh Gupta notifications@github.com
wrote:

> Got it. I also see the Abinash other people worked on a seperate repo
> https://github.com/abinashmeher999/eklavya-2015 for this year's work.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AGV-IIT-KGP/freezing-batman/issues/32#issuecomment-111948645
> .

## 

Regards,

Ayush Pandey
Department of Electrical Engineering
IIT Kharagpur
Personal Webpage: ayush9pandey.wix.com/ayushpandey

**Comment by shivamvats** [comment]
We do have code for jaus https://github.com/AGV-IIT-KGP/freezing-batman/tree/master/jaus from last year. It didn't work because we didn't spend much time on it and there were some hardware issues.
